server:
  port: 9000
  servlet:
    context-path: /api
spring:
  application:
    name: cards
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/api}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/api/eureka/
