server:
  port: 9000
  servlet:
    context-path: /api
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8871/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: prod
build:
  version: "1.0"

accounts:
  message: "Bem vindos ao EazyBank cards prod APIs "
  contactDetails:
    name: "RSDensenvolvimento"
    email: "rsdesenvolvimento@gmail.com"
  onCallSupport:
    - (999) 9999-9999
---
spring:
  config:
    activate:
      on-profile: qa
build:
  version: "2.0"

accounts:
  message: "Bem vindos ao EazyBank cards qa APIs "
  contactDetails:
    name: "RSDensenvolvimento"
    email: "rsdesenvolvimento@gmail.com"
  onCallSupport:
    - (999) 9999-9999
