server:
  port: 8090
  servlet:
    context-path: /api
spring:
  application:
    name: loans

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/api}
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/api/eureka/}
