server:
  port: 8070
  servlet:
    context-path: /api
spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/api"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
