server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: accounts
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/api/}
  # profiles:
  #   active: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/api/eureka/}
