server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: accounts
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8871/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

build:
  version: 1.0

accounts:
  message: "Bem-vindo ao microserviço de contas"
  contactDetails:
    name: "RSDesenvolvimento"
    email: "rsdesenvolvimento@gmail.com"
  onCallSupport:
    - (99) 99999-9999
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: "dev"
