server:
  port: 8071
  servlet:
    context-path: /api

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickelmySantos/spring-microservice-eazybank.git
          searchPaths: config
