server:
  port: 8071
  servlet:
    context-path: /api

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickelmySantos/spring-microservice-eazybank.git
          searchPaths: config
          default-label: feature-spring-cloud
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
  liveness-state:
    enabled: true
  endpoint:
    health:
      probes:
        enabled: true
