server:
  port: 8090
  servlet:
    context-path: /api
spring:
  application:
    name: loans
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
  jpa:
    show-sql: true
    hibernate:
      format_sql: false
      jakarta.persistence.schema-generation.scripts:
        action: drop-and-create
        create-source: metadata
        create-target: target/create.sql
        drop-source: metadata
        drop-target: target/drop.sql

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/api}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/api/eureka/}
